#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Visitors")]
public partial class VisitorsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public VisitorsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["VisitorsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public VisitorsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VisitorsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VisitorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VisitorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckOutAllVistorsDailyTask")]
	public int CheckOutAllVistorsDailyTask()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DepartmentsSearch")]
	public ISingleResult<DepartmentsSearchResult> DepartmentsSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Department_id", DbType="Int")] System.Nullable<int> department_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), department_id);
		return ((ISingleResult<DepartmentsSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DependentsAdd")]
	public int DependentsAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DependentName", DbType="NVarChar(255)")] string dependentName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DependentGeneder", DbType="Bit")] System.Nullable<bool> dependentGeneder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransactionID", DbType="Int")] System.Nullable<int> transactionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dependentName, dependentGeneder, transactionID, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(3)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllAltIDTypes")]
	public ISingleResult<GetAllAltIDTypesResult> GetAllAltIDTypes()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllAltIDTypesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDepartments")]
	public ISingleResult<GetAllDepartmentsResult> GetAllDepartments()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllDepartmentsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllUsers")]
	public ISingleResult<GetAllUsersResult> GetAllUsers()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllUsersResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDaysTransctions")]
	public ISingleResult<GetDaysTransctionsResult> GetDaysTransctions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> endDate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startDate, endDate);
		return ((ISingleResult<GetDaysTransctionsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getLastTransaction")]
	public ISingleResult<getLastTransactionResult> getLastTransaction([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VistorID", DbType="Int")] System.Nullable<int> vistorID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vistorID);
		return ((ISingleResult<getLastTransactionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsValidUser")]
	public ISingleResult<IsValidUserResult> IsValidUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		return ((ISingleResult<IsValidUserResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LogErrorsAdd")]
	public int LogErrorsAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExceptionMsg", DbType="NVarChar(100)")] string exceptionMsg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExceptionType", DbType="NVarChar(100)")] string exceptionType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExceptionStackTrace", DbType="NVarChar(MAX)")] string exceptionStackTrace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExceptionURL", DbType="NVarChar(100)")] string exceptionURL)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), exceptionMsg, exceptionType, exceptionStackTrace, exceptionURL);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NamesAdd")]
	public int NamesAdd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(1)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NamesEdit")]
	public int NamesEdit([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numberOfUse)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, numberOfUse);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NamesSearch")]
	public ISingleResult<NamesSearchResult> NamesSearch([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
		return ((ISingleResult<NamesSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PublicSearch")]
	public ISingleResult<PublicSearchResult> PublicSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlternativeID", DbType="NVarChar(50)")] string alternativeID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alternativeID);
		return ((ISingleResult<PublicSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TransationsCreate")]
	public int TransationsCreate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VistorID", DbType="Int")] System.Nullable<int> vistorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreationDate", DbType="DateTime")] System.Nullable<System.DateTime> creationDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Statues", DbType="Bit")] System.Nullable<bool> statues, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="NVarChar(MAX)")] string note, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberOfDependents", DbType="Int")] System.Nullable<int> numberOfDependents, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Department", DbType="Int")] System.Nullable<int> department, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Return", DbType="Int")] ref System.Nullable<int> @return, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vistorID, creationDate, userID, statues, note, numberOfDependents, department, @return, iD);
		@return = ((System.Nullable<int>)(result.GetParameterValue(7)));
		iD = ((System.Nullable<int>)(result.GetParameterValue(8)));
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UserIsLockedEdit")]
	public int UserIsLockedEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersAdd")]
	public int UsersAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(255)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserRole", DbType="NVarChar(50)")] string userRole, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserGender", DbType="Bit")] System.Nullable<bool> userGender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, userName, userRole, userGender, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(4)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersDelete")]
	public int UsersDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersEdit")]
	public int UsersEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(255)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserRole", DbType="NVarChar(50)")] string userRole, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserGender", DbType="Bit")] System.Nullable<bool> userGender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, userName, userRole, userGender, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(4)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersSearch")]
	public ISingleResult<UsersSearchResult> UsersSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="NVarChar(50)")] string userID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		return ((ISingleResult<UsersSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VistorsAdd")]
	public int VistorsAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalID", DbType="NVarChar(50)")] string nationalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Bit")] System.Nullable<bool> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalIDImg", DbType="NVarChar(100)")] string nationalIDImg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="NVarChar(50)")] string createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditedBy", DbType="NVarChar(50)")] string editedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditDate", DbType="DateTime")] System.Nullable<System.DateTime> editDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlternativeID", DbType="NVarChar(20)")] string alternativeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> alternativeIDType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryID", DbType="Int")] System.Nullable<int> countryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] ref System.Nullable<int> iD)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nationalID, name, gender, nationalIDImg, mobile, createdBy, editedBy, editDate, alternativeID, alternativeIDType, countryID, result, iD);
		result = ((System.Nullable<int>)(result1.GetParameterValue(11)));
		iD = ((System.Nullable<int>)(result1.GetParameterValue(12)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VistorsDelete")]
	public int VistorsDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VistorsEdit")]
	public int VistorsEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalID", DbType="NVarChar(50)")] string nationalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Bit")] System.Nullable<bool> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalIDImg", DbType="NVarChar(100)")] string nationalIDImg, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditedBy", DbType="NVarChar(50)")] string editedBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EditDate", DbType="DateTime")] System.Nullable<System.DateTime> editDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlternativeID", DbType="NVarChar(20)")] string alternativeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> alternativeIDType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryID", DbType="Int")] System.Nullable<int> countryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nationalID, name, gender, nationalIDImg, mobile, editedBy, editDate, alternativeID, alternativeIDType, countryID, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(11)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VistorsSearch")]
	public ISingleResult<VistorsSearchResult> VistorsSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NChar(250)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="NChar(256)")] string mobileNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CivilId", DbType="NChar(256)")] string civilId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Bit")] System.Nullable<bool> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitorID", DbType="Int")] System.Nullable<int> visitorID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, mobileNo, civilId, gender, visitorID);
		return ((ISingleResult<VistorsSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VistorTacking")]
	public ISingleResult<VistorTackingResult> VistorTacking([global::System.Data.Linq.Mapping.ParameterAttribute(Name="VistorID", DbType="Int")] System.Nullable<int> vistorID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vistorID, startDate, endDate);
		return ((ISingleResult<VistorTackingResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCheckInVistors")]
	public ISingleResult<GetCheckInVistorsResult> GetCheckInVistors([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Bit")] System.Nullable<bool> gender)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gender);
		return ((ISingleResult<GetCheckInVistorsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getVistorsGroupByID")]
	public ISingleResult<getVistorsGroupByIDResult> getVistorsGroupByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID1", DbType="VarChar(255)")] string vistor_ID1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string vistor_ID2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string vistor_ID3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string vistor_ID4, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string vistor_ID5, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string vistor_ID6)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vistor_ID1, vistor_ID2, vistor_ID3, vistor_ID4, vistor_ID5, vistor_ID6);
		return ((ISingleResult<getVistorsGroupByIDResult>)(result.ReturnValue));
	}
}

public partial class DepartmentsSearchResult
{
	
	private int _Department_id;
	
	private string _Department_Name;
	
	private string _Department_Domain;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private System.Nullable<int> _Priority;
	
	public DepartmentsSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_id", DbType="Int NOT NULL")]
	public int Department_id
	{
		get
		{
			return this._Department_id;
		}
		set
		{
			if ((this._Department_id != value))
			{
				this._Department_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Department_Name
	{
		get
		{
			return this._Department_Name;
		}
		set
		{
			if ((this._Department_Name != value))
			{
				this._Department_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Domain", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Department_Domain
	{
		get
		{
			return this._Department_Domain;
		}
		set
		{
			if ((this._Department_Domain != value))
			{
				this._Department_Domain = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
	public System.Nullable<int> Priority
	{
		get
		{
			return this._Priority;
		}
		set
		{
			if ((this._Priority != value))
			{
				this._Priority = value;
			}
		}
	}
}

public partial class GetAllAltIDTypesResult
{
	
	private int _id;
	
	private string _typeAr;
	
	private string _typeEn;
	
	public GetAllAltIDTypesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeAr", DbType="NVarChar(50)")]
	public string typeAr
	{
		get
		{
			return this._typeAr;
		}
		set
		{
			if ((this._typeAr != value))
			{
				this._typeAr = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeEn", DbType="NVarChar(50)")]
	public string typeEn
	{
		get
		{
			return this._typeEn;
		}
		set
		{
			if ((this._typeEn != value))
			{
				this._typeEn = value;
			}
		}
	}
}

public partial class GetAllDepartmentsResult
{
	
	private int _Department_id;
	
	private string _Department_Name;
	
	private string _Department_Domain;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private string _Department_Name_En;
	
	private System.Nullable<int> _Priority;
	
	public GetAllDepartmentsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_id", DbType="Int NOT NULL")]
	public int Department_id
	{
		get
		{
			return this._Department_id;
		}
		set
		{
			if ((this._Department_id != value))
			{
				this._Department_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Department_Name
	{
		get
		{
			return this._Department_Name;
		}
		set
		{
			if ((this._Department_Name != value))
			{
				this._Department_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Domain", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Department_Domain
	{
		get
		{
			return this._Department_Domain;
		}
		set
		{
			if ((this._Department_Domain != value))
			{
				this._Department_Domain = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name_En", DbType="NVarChar(50)")]
	public string Department_Name_En
	{
		get
		{
			return this._Department_Name_En;
		}
		set
		{
			if ((this._Department_Name_En != value))
			{
				this._Department_Name_En = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
	public System.Nullable<int> Priority
	{
		get
		{
			return this._Priority;
		}
		set
		{
			if ((this._Priority != value))
			{
				this._Priority = value;
			}
		}
	}
}

public partial class GetAllUsersResult
{
	
	private string _UserID;
	
	private string _UserName;
	
	private string _UserRole;
	
	private System.Nullable<bool> _UserIsLocked;
	
	private bool _UserGender;
	
	private System.Nullable<System.DateTime> _CreationDate;
	
	public GetAllUsersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this._UserName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserRole
	{
		get
		{
			return this._UserRole;
		}
		set
		{
			if ((this._UserRole != value))
			{
				this._UserRole = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIsLocked", DbType="Bit")]
	public System.Nullable<bool> UserIsLocked
	{
		get
		{
			return this._UserIsLocked;
		}
		set
		{
			if ((this._UserIsLocked != value))
			{
				this._UserIsLocked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGender", DbType="Bit NOT NULL")]
	public bool UserGender
	{
		get
		{
			return this._UserGender;
		}
		set
		{
			if ((this._UserGender != value))
			{
				this._UserGender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreationDate
	{
		get
		{
			return this._CreationDate;
		}
		set
		{
			if ((this._CreationDate != value))
			{
				this._CreationDate = value;
			}
		}
	}
}

public partial class GetDaysTransctionsResult
{
	
	private System.Nullable<System.DateTime> _TransactionCreationDate;
	
	private System.Nullable<int> _Male;
	
	private System.Nullable<int> _Female;
	
	private System.Nullable<int> _Per1;
	
	private System.Nullable<int> _Per2;
	
	private System.Nullable<int> _Per3;
	
	private System.Nullable<int> _Per4;
	
	private System.Nullable<int> _Per5;
	
	private System.Nullable<int> _Per6;
	
	private System.Nullable<int> _Per7;
	
	private System.Nullable<int> _Per8;
	
	private System.Nullable<int> _Per9;
	
	private System.Nullable<int> _Per10;
	
	private System.Nullable<int> _Per11;
	
	private System.Nullable<int> _Total;
	
	public GetDaysTransctionsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionCreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> TransactionCreationDate
	{
		get
		{
			return this._TransactionCreationDate;
		}
		set
		{
			if ((this._TransactionCreationDate != value))
			{
				this._TransactionCreationDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Male", DbType="Int")]
	public System.Nullable<int> Male
	{
		get
		{
			return this._Male;
		}
		set
		{
			if ((this._Male != value))
			{
				this._Male = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Female", DbType="Int")]
	public System.Nullable<int> Female
	{
		get
		{
			return this._Female;
		}
		set
		{
			if ((this._Female != value))
			{
				this._Female = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per1", DbType="Int")]
	public System.Nullable<int> Per1
	{
		get
		{
			return this._Per1;
		}
		set
		{
			if ((this._Per1 != value))
			{
				this._Per1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per2", DbType="Int")]
	public System.Nullable<int> Per2
	{
		get
		{
			return this._Per2;
		}
		set
		{
			if ((this._Per2 != value))
			{
				this._Per2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per3", DbType="Int")]
	public System.Nullable<int> Per3
	{
		get
		{
			return this._Per3;
		}
		set
		{
			if ((this._Per3 != value))
			{
				this._Per3 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per4", DbType="Int")]
	public System.Nullable<int> Per4
	{
		get
		{
			return this._Per4;
		}
		set
		{
			if ((this._Per4 != value))
			{
				this._Per4 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per5", DbType="Int")]
	public System.Nullable<int> Per5
	{
		get
		{
			return this._Per5;
		}
		set
		{
			if ((this._Per5 != value))
			{
				this._Per5 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per6", DbType="Int")]
	public System.Nullable<int> Per6
	{
		get
		{
			return this._Per6;
		}
		set
		{
			if ((this._Per6 != value))
			{
				this._Per6 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per7", DbType="Int")]
	public System.Nullable<int> Per7
	{
		get
		{
			return this._Per7;
		}
		set
		{
			if ((this._Per7 != value))
			{
				this._Per7 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per8", DbType="Int")]
	public System.Nullable<int> Per8
	{
		get
		{
			return this._Per8;
		}
		set
		{
			if ((this._Per8 != value))
			{
				this._Per8 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per9", DbType="Int")]
	public System.Nullable<int> Per9
	{
		get
		{
			return this._Per9;
		}
		set
		{
			if ((this._Per9 != value))
			{
				this._Per9 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per10", DbType="Int")]
	public System.Nullable<int> Per10
	{
		get
		{
			return this._Per10;
		}
		set
		{
			if ((this._Per10 != value))
			{
				this._Per10 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Per11", DbType="Int")]
	public System.Nullable<int> Per11
	{
		get
		{
			return this._Per11;
		}
		set
		{
			if ((this._Per11 != value))
			{
				this._Per11 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
	public System.Nullable<int> Total
	{
		get
		{
			return this._Total;
		}
		set
		{
			if ((this._Total != value))
			{
				this._Total = value;
			}
		}
	}
}

public partial class getLastTransactionResult
{
	
	private bool _Statues;
	
	public getLastTransactionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statues", DbType="Bit NOT NULL")]
	public bool Statues
	{
		get
		{
			return this._Statues;
		}
		set
		{
			if ((this._Statues != value))
			{
				this._Statues = value;
			}
		}
	}
}

public partial class IsValidUserResult
{
	
	private string _UserID;
	
	private string _UserName;
	
	private string _UserRole;
	
	private System.Nullable<bool> _UserIsLocked;
	
	private bool _UserGender;
	
	private System.Nullable<System.DateTime> _CreationDate;
	
	public IsValidUserResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this._UserName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserRole
	{
		get
		{
			return this._UserRole;
		}
		set
		{
			if ((this._UserRole != value))
			{
				this._UserRole = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIsLocked", DbType="Bit")]
	public System.Nullable<bool> UserIsLocked
	{
		get
		{
			return this._UserIsLocked;
		}
		set
		{
			if ((this._UserIsLocked != value))
			{
				this._UserIsLocked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGender", DbType="Bit NOT NULL")]
	public bool UserGender
	{
		get
		{
			return this._UserGender;
		}
		set
		{
			if ((this._UserGender != value))
			{
				this._UserGender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreationDate
	{
		get
		{
			return this._CreationDate;
		}
		set
		{
			if ((this._CreationDate != value))
			{
				this._CreationDate = value;
			}
		}
	}
}

public partial class NamesSearchResult
{
	
	private string _name;
	
	public NamesSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
}

public partial class PublicSearchResult
{
	
	private string _Name;
	
	private string _UserID;
	
	private string _MobileNo;
	
	private string _CivilId;
	
	private System.Nullable<bool> _Gender;
	
	private System.DateTime _LastModified;
	
	private string _Country;
	
	private int _VisitorID;
	
	public PublicSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(250)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NChar(256) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NChar(256) NOT NULL", CanBeNull=false)]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CivilId", DbType="NChar(256)")]
	public string CivilId
	{
		get
		{
			return this._CivilId;
		}
		set
		{
			if ((this._CivilId != value))
			{
				this._CivilId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModified", DbType="DateTime NOT NULL")]
	public System.DateTime LastModified
	{
		get
		{
			return this._LastModified;
		}
		set
		{
			if ((this._LastModified != value))
			{
				this._LastModified = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitorID", DbType="Int NOT NULL")]
	public int VisitorID
	{
		get
		{
			return this._VisitorID;
		}
		set
		{
			if ((this._VisitorID != value))
			{
				this._VisitorID = value;
			}
		}
	}
}

public partial class UsersSearchResult
{
	
	private string _UserID;
	
	private string _UserName;
	
	private string _UserRole;
	
	private System.Nullable<bool> _UserIsLocked;
	
	private bool _UserGender;
	
	private System.Nullable<System.DateTime> _CreationDate;
	
	public UsersSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this._UserName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserRole", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string UserRole
	{
		get
		{
			return this._UserRole;
		}
		set
		{
			if ((this._UserRole != value))
			{
				this._UserRole = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserIsLocked", DbType="Bit")]
	public System.Nullable<bool> UserIsLocked
	{
		get
		{
			return this._UserIsLocked;
		}
		set
		{
			if ((this._UserIsLocked != value))
			{
				this._UserIsLocked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserGender", DbType="Bit NOT NULL")]
	public bool UserGender
	{
		get
		{
			return this._UserGender;
		}
		set
		{
			if ((this._UserGender != value))
			{
				this._UserGender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreationDate
	{
		get
		{
			return this._CreationDate;
		}
		set
		{
			if ((this._CreationDate != value))
			{
				this._CreationDate = value;
			}
		}
	}
}

public partial class VistorsSearchResult
{
	
	private string _Name;
	
	private string _UserID;
	
	private string _MobileNo;
	
	private string _CivilId;
	
	private System.Nullable<bool> _Gender;
	
	private System.Nullable<System.DateTime> _LastModified;
	
	private string _Country;
	
	private System.Nullable<int> _VisitorID;
	
	public VistorsSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NChar(250)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NChar(256)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NChar(256)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CivilId", DbType="NChar(256)")]
	public string CivilId
	{
		get
		{
			return this._CivilId;
		}
		set
		{
			if ((this._CivilId != value))
			{
				this._CivilId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModified", DbType="DateTime")]
	public System.Nullable<System.DateTime> LastModified
	{
		get
		{
			return this._LastModified;
		}
		set
		{
			if ((this._LastModified != value))
			{
				this._LastModified = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(MAX)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitorID", DbType="Int")]
	public System.Nullable<int> VisitorID
	{
		get
		{
			return this._VisitorID;
		}
		set
		{
			if ((this._VisitorID != value))
			{
				this._VisitorID = value;
			}
		}
	}
}

public partial class VistorTackingResult
{
	
	private string _VistorName;
	
	private string _CreatedBy;
	
	private bool _Statues;
	
	private System.Nullable<int> _Department;
	
	private System.DateTime _TransactionCreationDate;
	
	private string _Note;
	
	private System.Nullable<int> _NumberOfDependents;
	
	public VistorTackingResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VistorName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string VistorName
	{
		get
		{
			return this._VistorName;
		}
		set
		{
			if ((this._VistorName != value))
			{
				this._VistorName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this._CreatedBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statues", DbType="Bit NOT NULL")]
	public bool Statues
	{
		get
		{
			return this._Statues;
		}
		set
		{
			if ((this._Statues != value))
			{
				this._Statues = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
	public System.Nullable<int> Department
	{
		get
		{
			return this._Department;
		}
		set
		{
			if ((this._Department != value))
			{
				this._Department = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionCreationDate", DbType="DateTime NOT NULL")]
	public System.DateTime TransactionCreationDate
	{
		get
		{
			return this._TransactionCreationDate;
		}
		set
		{
			if ((this._TransactionCreationDate != value))
			{
				this._TransactionCreationDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(MAX)")]
	public string Note
	{
		get
		{
			return this._Note;
		}
		set
		{
			if ((this._Note != value))
			{
				this._Note = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfDependents", DbType="Int")]
	public System.Nullable<int> NumberOfDependents
	{
		get
		{
			return this._NumberOfDependents;
		}
		set
		{
			if ((this._NumberOfDependents != value))
			{
				this._NumberOfDependents = value;
			}
		}
	}
}

public partial class GetCheckInVistorsResult
{
	
	private System.Nullable<int> _ID;
	
	private System.Nullable<bool> _st;
	
	private string _UserID;
	
	private string _Name;
	
	private System.Nullable<bool> _Gender;
	
	private string _MobileNo;
	
	private string _CivilId;
	
	private System.Nullable<int> _VisitorID;
	
	public GetCheckInVistorsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
	public System.Nullable<int> ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_st", DbType="Bit")]
	public System.Nullable<bool> st
	{
		get
		{
			return this._st;
		}
		set
		{
			if ((this._st != value))
			{
				this._st = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NChar(256)")]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this._UserID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NChar(256)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CivilId", DbType="NChar(256)")]
	public string CivilId
	{
		get
		{
			return this._CivilId;
		}
		set
		{
			if ((this._CivilId != value))
			{
				this._CivilId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitorID", DbType="Int")]
	public System.Nullable<int> VisitorID
	{
		get
		{
			return this._VisitorID;
		}
		set
		{
			if ((this._VisitorID != value))
			{
				this._VisitorID = value;
			}
		}
	}
}

public partial class getVistorsGroupByIDResult
{
	
	private System.Nullable<int> _ID;
	
	private System.Nullable<System.Guid> _VistorID;
	
	private string _NationalID;
	
	private string _Name;
	
	private System.Nullable<bool> _Gender;
	
	private string _NationalIDImg;
	
	private string _Mobile;
	
	private string _AlternativeID;
	
	private System.Nullable<int> _alternativeIDType;
	
	private string _EditedBy;
	
	private System.Nullable<int> _CountryID;
	
	private System.Nullable<System.DateTime> _EditDate;
	
	private string _CreatedBy;
	
	private System.Nullable<System.DateTime> _CreationDate;
	
	private string _CountryName;
	
	private string _typeAr;
	
	public getVistorsGroupByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
	public System.Nullable<int> ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VistorID", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> VistorID
	{
		get
		{
			return this._VistorID;
		}
		set
		{
			if ((this._VistorID != value))
			{
				this._VistorID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalID", DbType="NVarChar(50)")]
	public string NationalID
	{
		get
		{
			return this._NationalID;
		}
		set
		{
			if ((this._NationalID != value))
			{
				this._NationalID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit")]
	public System.Nullable<bool> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalIDImg", DbType="NVarChar(100)")]
	public string NationalIDImg
	{
		get
		{
			return this._NationalIDImg;
		}
		set
		{
			if ((this._NationalIDImg != value))
			{
				this._NationalIDImg = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this._Mobile = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternativeID", DbType="NVarChar(50)")]
	public string AlternativeID
	{
		get
		{
			return this._AlternativeID;
		}
		set
		{
			if ((this._AlternativeID != value))
			{
				this._AlternativeID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alternativeIDType", DbType="Int")]
	public System.Nullable<int> alternativeIDType
	{
		get
		{
			return this._alternativeIDType;
		}
		set
		{
			if ((this._alternativeIDType != value))
			{
				this._alternativeIDType = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditedBy", DbType="NVarChar(50)")]
	public string EditedBy
	{
		get
		{
			return this._EditedBy;
		}
		set
		{
			if ((this._EditedBy != value))
			{
				this._EditedBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="Int")]
	public System.Nullable<int> CountryID
	{
		get
		{
			return this._CountryID;
		}
		set
		{
			if ((this._CountryID != value))
			{
				this._CountryID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> EditDate
	{
		get
		{
			return this._EditDate;
		}
		set
		{
			if ((this._EditDate != value))
			{
				this._EditDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this._CreatedBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreationDate
	{
		get
		{
			return this._CreationDate;
		}
		set
		{
			if ((this._CreationDate != value))
			{
				this._CreationDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="NVarChar(50)")]
	public string CountryName
	{
		get
		{
			return this._CountryName;
		}
		set
		{
			if ((this._CountryName != value))
			{
				this._CountryName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeAr", DbType="NVarChar(50)")]
	public string typeAr
	{
		get
		{
			return this._typeAr;
		}
		set
		{
			if ((this._typeAr != value))
			{
				this._typeAr = value;
			}
		}
	}
}
#pragma warning restore 1591
